2023-06-22 15:14:59 Calling on_part_begin with no data
2023-06-22 15:14:59 Calling on_header_field with data[54:73]
2023-06-22 15:14:59 Calling on_header_value with data[75:148]
2023-06-22 15:14:59 Calling on_header_end with no data
2023-06-22 15:14:59 Calling on_header_field with data[150:162]
2023-06-22 15:14:59 Calling on_header_value with data[164:173]
2023-06-22 15:14:59 Calling on_header_end with no data
2023-06-22 15:14:59 Calling on_headers_finished with no data
2023-06-22 15:14:59 Calling on_part_data with data[177:65713]
2023-06-22 15:14:59 Calling on_part_data with data[0:6107]
2023-06-22 15:14:59 Calling on_part_data with data[0:1]
2023-06-22 15:14:59 Calling on_part_data with data[6108:262144]
2023-06-22 15:14:59 Calling on_part_data with data[0:236841]
2023-06-22 15:14:59 Calling on_part_data with data[0:1]
2023-06-22 15:14:59 Calling on_part_data with data[236842:262144]
2023-06-22 15:14:59 Calling on_part_data with data[0:230870]
2023-06-22 15:14:59 Calling on_part_data with data[0:1]
2023-06-22 15:14:59 Calling on_part_data with data[230871:262144]
2023-06-22 15:14:59 Calling on_part_data with data[0:10921]
2023-06-22 15:14:59 Calling on_part_data with data[0:1]
2023-06-22 15:14:59 Calling on_part_data with data[10922:81825]
2023-06-22 15:14:59 Calling on_part_data with data[0:1]
2023-06-22 15:14:59 Calling on_part_data with data[81826:187007]
2023-06-22 15:14:59 Calling on_part_data with data[0:1]
2023-06-22 15:14:59 Calling on_part_data with data[187008:262144]
2023-06-22 15:14:59 Calling on_part_data with data[0:25359]
2023-06-22 15:14:59 Calling on_part_end with no data
2023-06-22 15:14:59 Calling on_end with no data
2023-06-22 15:14:59 Processing audio
2023-06-22 15:14:59 An error occurred during audio processing:
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 56, in audio
    response = openai.Audio.transcribe("whisper-1", audio_file, response_format="text",language="en")
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_resources/audio.py", line 55, in transcribe
    requestor, files, data = cls._prepare_request(
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_resources/audio.py", line 28, in _prepare_request
    requestor = api_requestor.APIRequestor(
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
2023-06-22 15:16:21 *************App Started**************
2023-06-22 15:16:21 Using selector: EpollSelector
2023-06-22 15:16:26 Calling on_part_begin with no data
2023-06-22 15:16:26 Calling on_header_field with data[54:73]
2023-06-22 15:16:26 Calling on_header_value with data[75:148]
2023-06-22 15:16:26 Calling on_header_end with no data
2023-06-22 15:16:26 Calling on_header_field with data[150:162]
2023-06-22 15:16:26 Calling on_header_value with data[164:173]
2023-06-22 15:16:26 Calling on_header_end with no data
2023-06-22 15:16:26 Calling on_headers_finished with no data
2023-06-22 15:16:26 Calling on_part_data with data[177:25565]
2023-06-22 15:16:26 Calling on_part_data with data[0:1]
2023-06-22 15:16:26 Calling on_part_data with data[25566:65659]
2023-06-22 15:16:26 Calling on_part_data with data[0:6161]
2023-06-22 15:16:26 Calling on_part_data with data[0:1]
2023-06-22 15:16:26 Calling on_part_data with data[6162:281573]
2023-06-22 15:16:26 Calling on_part_data with data[0:1]
2023-06-22 15:16:26 Calling on_part_data with data[281574:294939]
2023-06-22 15:16:26 Calling on_part_data with data[0:192624]
2023-06-22 15:16:26 Calling on_part_data with data[0:1]
2023-06-22 15:16:26 Calling on_part_data with data[192625:230617]
2023-06-22 15:16:26 Calling on_part_data with data[0:1]
2023-06-22 15:16:26 Calling on_part_data with data[230618:262144]
2023-06-22 15:16:26 Calling on_part_data with data[0:198129]
2023-06-22 15:16:26 Calling on_part_data with data[0:1]
2023-06-22 15:16:26 Calling on_part_data with data[198130:262144]
2023-06-22 15:16:26 Calling on_part_data with data[0:254762]
2023-06-22 15:16:26 Calling on_part_end with no data
2023-06-22 15:16:26 Calling on_end with no data
2023-06-22 15:16:26 Processing audio
2023-06-22 15:16:26 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:16:26 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:16:26 Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-06-22 15:16:26 Starting new HTTPS connection (1): api.openai.com:443
2023-06-22 15:17:49 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 200 None
2023-06-22 15:17:49 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=5996 request_id=b577a649abe25687ed234b4f3512801e response_code=200
2023-06-22 15:17:49 An error occurred during audio processing:
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 57, in audio
    transcript = response['text']
TypeError: string indices must be integers
2023-06-22 15:20:36 Calling on_part_begin with no data
2023-06-22 15:20:36 Calling on_header_field with data[54:73]
2023-06-22 15:20:36 Calling on_header_value with data[75:130]
2023-06-22 15:20:36 Calling on_header_end with no data
2023-06-22 15:20:36 Calling on_header_field with data[132:144]
2023-06-22 15:20:36 Calling on_header_value with data[146:156]
2023-06-22 15:20:36 Calling on_header_end with no data
2023-06-22 15:20:36 Calling on_headers_finished with no data
2023-06-22 15:20:36 Calling on_part_data with data[160:25548]
2023-06-22 15:20:36 Calling on_part_data with data[0:1]
2023-06-22 15:20:36 Calling on_part_data with data[25549:65696]
2023-06-22 15:20:36 Calling on_part_data with data[0:6107]
2023-06-22 15:20:36 Calling on_part_data with data[0:1]
2023-06-22 15:20:36 Calling on_part_data with data[6108:89599]
2023-06-22 15:20:36 Calling on_part_data with data[0:1]
2023-06-22 15:20:36 Calling on_part_data with data[89600:262144]
2023-06-22 15:20:36 Calling on_part_data with data[0:137181]
2023-06-22 15:20:36 Calling on_part_data with data[0:1]
2023-06-22 15:20:36 Calling on_part_data with data[137182:187194]
2023-06-22 15:20:36 Calling on_part_data with data[0:1]
2023-06-22 15:20:36 Calling on_part_data with data[187195:262144]
2023-06-22 15:20:36 Calling on_part_data with data[0:230870]
2023-06-22 15:20:36 Calling on_part_data with data[0:1]
2023-06-22 15:20:36 Calling on_part_data with data[230871:262144]
2023-06-22 15:20:36 Calling on_part_data with data[0:10921]
2023-06-22 15:20:36 Calling on_part_data with data[0:1]
2023-06-22 15:20:36 Calling on_part_data with data[10922:150062]
2023-06-22 15:20:36 Calling on_part_data with data[0:1]
2023-06-22 15:20:36 Calling on_part_data with data[150063:262144]
2023-06-22 15:20:36 Calling on_part_data with data[0:25359]
2023-06-22 15:20:36 Calling on_part_end with no data
2023-06-22 15:20:36 Calling on_end with no data
2023-06-22 15:20:36 Processing audio
2023-06-22 15:20:36 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:20:36 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:20:36 Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-06-22 15:20:36 Starting new HTTPS connection (1): api.openai.com:443
2023-06-22 15:21:24 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 200 None
2023-06-22 15:21:24 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=6566 request_id=a24fa8981ffc2f8e317d1816e6fd1669 response_code=200
2023-06-22 15:21:24 An error occurred during audio processing:
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 57, in audio
    print(response)
TypeError: string indices must be integers
2023-06-22 15:22:51 Calling on_part_begin with no data
2023-06-22 15:22:51 Calling on_header_field with data[54:73]
2023-06-22 15:22:51 Calling on_header_value with data[75:130]
2023-06-22 15:22:51 Calling on_header_end with no data
2023-06-22 15:22:51 Calling on_header_field with data[132:144]
2023-06-22 15:22:51 Calling on_header_value with data[146:156]
2023-06-22 15:22:51 Calling on_header_end with no data
2023-06-22 15:22:51 Calling on_headers_finished with no data
2023-06-22 15:22:51 Calling on_part_data with data[160:65696]
2023-06-22 15:22:51 Calling on_part_data with data[0:6107]
2023-06-22 15:22:51 Calling on_part_data with data[0:1]
2023-06-22 15:22:51 Calling on_part_data with data[6108:89599]
2023-06-22 15:22:51 Calling on_part_data with data[0:1]
2023-06-22 15:22:51 Calling on_part_data with data[89600:128795]
2023-06-22 15:22:51 Calling on_part_data with data[0:1]
2023-06-22 15:22:51 Calling on_part_data with data[128796:262144]
2023-06-22 15:22:51 Calling on_part_data with data[0:236841]
2023-06-22 15:22:51 Calling on_part_data with data[0:1]
2023-06-22 15:22:51 Calling on_part_data with data[236842:262144]
2023-06-22 15:22:51 Calling on_part_data with data[0:177876]
2023-06-22 15:22:51 Calling on_part_data with data[0:1]
2023-06-22 15:22:51 Calling on_part_data with data[177877:262144]
2023-06-22 15:22:51 Calling on_part_data with data[0:10921]
2023-06-22 15:22:51 Calling on_part_data with data[0:1]
2023-06-22 15:22:51 Calling on_part_data with data[10922:163810]
2023-06-22 15:22:51 Calling on_part_data with data[0:1]
2023-06-22 15:22:51 Calling on_part_data with data[163811:262144]
2023-06-22 15:22:51 Calling on_part_data with data[0:25359]
2023-06-22 15:22:51 Calling on_part_end with no data
2023-06-22 15:22:51 Calling on_end with no data
2023-06-22 15:22:51 Processing audio
2023-06-22 15:22:51 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:22:51 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:22:51 Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-06-22 15:22:51 Starting new HTTPS connection (1): api.openai.com:443
2023-06-22 15:24:27 Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

2023-06-22 15:25:09 Calling on_part_begin with no data
2023-06-22 15:25:09 Calling on_header_field with data[54:73]
2023-06-22 15:25:09 Calling on_header_value with data[75:130]
2023-06-22 15:25:09 Calling on_header_end with no data
2023-06-22 15:25:09 Calling on_header_field with data[132:144]
2023-06-22 15:25:09 Calling on_header_value with data[146:156]
2023-06-22 15:25:09 Calling on_header_end with no data
2023-06-22 15:25:09 Calling on_headers_finished with no data
2023-06-22 15:25:09 Calling on_part_data with data[160:25548]
2023-06-22 15:25:09 Calling on_part_data with data[0:1]
2023-06-22 15:25:09 Calling on_part_data with data[25549:65696]
2023-06-22 15:25:09 Calling on_part_data with data[0:6107]
2023-06-22 15:25:09 Calling on_part_data with data[0:1]
2023-06-22 15:25:09 Calling on_part_data with data[6108:89599]
2023-06-22 15:25:09 Calling on_part_data with data[0:1]
2023-06-22 15:25:09 Calling on_part_data with data[89600:262144]
2023-06-22 15:25:09 Calling on_part_data with data[0:137181]
2023-06-22 15:25:09 Calling on_part_data with data[0:1]
2023-06-22 15:25:09 Calling on_part_data with data[137182:187194]
2023-06-22 15:25:09 Calling on_part_data with data[0:1]
2023-06-22 15:25:09 Calling on_part_data with data[187195:262144]
2023-06-22 15:25:09 Calling on_part_data with data[0:230870]
2023-06-22 15:25:09 Calling on_part_data with data[0:1]
2023-06-22 15:25:09 Calling on_part_data with data[230871:262144]
2023-06-22 15:25:09 Calling on_part_data with data[0:10921]
2023-06-22 15:25:09 Calling on_part_data with data[0:1]
2023-06-22 15:25:09 Calling on_part_data with data[10922:150062]
2023-06-22 15:25:09 Calling on_part_data with data[0:1]
2023-06-22 15:25:09 Calling on_part_data with data[150063:262144]
2023-06-22 15:25:09 Calling on_part_data with data[0:25359]
2023-06-22 15:25:09 Calling on_part_end with no data
2023-06-22 15:25:09 Calling on_end with no data
2023-06-22 15:25:09 Processing audio
2023-06-22 15:25:09 Failed to process audio file
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 56, in audio
    response = openai.Audio.transcribe("whisper-1", audio_file, response_format="text",language="en")
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_resources/audio.py", line 55, in transcribe
    requestor, files, data = cls._prepare_request(
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_resources/audio.py", line 28, in _prepare_request
    requestor = api_requestor.APIRequestor(
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
2023-06-22 15:26:09 Calling on_part_begin with no data
2023-06-22 15:26:09 Calling on_header_field with data[54:73]
2023-06-22 15:26:09 Calling on_header_value with data[75:130]
2023-06-22 15:26:09 Calling on_header_end with no data
2023-06-22 15:26:09 Calling on_header_field with data[132:144]
2023-06-22 15:26:09 Calling on_header_value with data[146:156]
2023-06-22 15:26:09 Calling on_header_end with no data
2023-06-22 15:26:09 Calling on_headers_finished with no data
2023-06-22 15:26:09 Calling on_part_data with data[160:25548]
2023-06-22 15:26:09 Calling on_part_data with data[0:1]
2023-06-22 15:26:09 Calling on_part_data with data[25549:65696]
2023-06-22 15:26:09 Calling on_part_data with data[0:6107]
2023-06-22 15:26:09 Calling on_part_data with data[0:1]
2023-06-22 15:26:09 Calling on_part_data with data[6108:89599]
2023-06-22 15:26:09 Calling on_part_data with data[0:1]
2023-06-22 15:26:09 Calling on_part_data with data[89600:262144]
2023-06-22 15:26:09 Calling on_part_data with data[0:137181]
2023-06-22 15:26:09 Calling on_part_data with data[0:1]
2023-06-22 15:26:09 Calling on_part_data with data[137182:187194]
2023-06-22 15:26:09 Calling on_part_data with data[0:1]
2023-06-22 15:26:09 Calling on_part_data with data[187195:262144]
2023-06-22 15:26:09 Calling on_part_data with data[0:230870]
2023-06-22 15:26:09 Calling on_part_data with data[0:1]
2023-06-22 15:26:09 Calling on_part_data with data[230871:262144]
2023-06-22 15:26:09 Calling on_part_data with data[0:10921]
2023-06-22 15:26:09 Calling on_part_data with data[0:1]
2023-06-22 15:26:09 Calling on_part_data with data[10922:150062]
2023-06-22 15:26:09 Calling on_part_data with data[0:1]
2023-06-22 15:26:09 Calling on_part_data with data[150063:262144]
2023-06-22 15:26:09 Calling on_part_data with data[0:25359]
2023-06-22 15:26:09 Calling on_part_end with no data
2023-06-22 15:26:09 Calling on_end with no data
2023-06-22 15:26:09 Processing audio
2023-06-22 15:26:09 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:26:09 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:26:09 Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-06-22 15:26:09 Starting new HTTPS connection (1): api.openai.com:443
2023-06-22 15:27:16 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 200 None
2023-06-22 15:27:16 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=5325 request_id=b5be5de471bc13ad95d0d60f9db36ec1 response_code=200
2023-06-22 15:27:16 Failed to process audio file
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 58, in audio
    transcript = response[0]['text']
TypeError: string indices must be integers
2023-06-22 15:27:46 Calling on_part_begin with no data
2023-06-22 15:27:46 Calling on_header_field with data[54:73]
2023-06-22 15:27:46 Calling on_header_value with data[75:130]
2023-06-22 15:27:46 Calling on_header_end with no data
2023-06-22 15:27:46 Calling on_header_field with data[132:144]
2023-06-22 15:27:46 Calling on_header_value with data[146:156]
2023-06-22 15:27:46 Calling on_header_end with no data
2023-06-22 15:27:46 Calling on_headers_finished with no data
2023-06-22 15:27:46 Calling on_part_data with data[160:25548]
2023-06-22 15:27:46 Calling on_part_data with data[0:1]
2023-06-22 15:27:46 Calling on_part_data with data[25549:65696]
2023-06-22 15:27:46 Calling on_part_data with data[0:6107]
2023-06-22 15:27:46 Calling on_part_data with data[0:1]
2023-06-22 15:27:46 Calling on_part_data with data[6108:89599]
2023-06-22 15:27:46 Calling on_part_data with data[0:1]
2023-06-22 15:27:46 Calling on_part_data with data[89600:262144]
2023-06-22 15:27:46 Calling on_part_data with data[0:137181]
2023-06-22 15:27:46 Calling on_part_data with data[0:1]
2023-06-22 15:27:46 Calling on_part_data with data[137182:187194]
2023-06-22 15:27:46 Calling on_part_data with data[0:1]
2023-06-22 15:27:46 Calling on_part_data with data[187195:262144]
2023-06-22 15:27:46 Calling on_part_data with data[0:230870]
2023-06-22 15:27:46 Calling on_part_data with data[0:1]
2023-06-22 15:27:46 Calling on_part_data with data[230871:262144]
2023-06-22 15:27:46 Calling on_part_data with data[0:10921]
2023-06-22 15:27:46 Calling on_part_data with data[0:1]
2023-06-22 15:27:46 Calling on_part_data with data[10922:150062]
2023-06-22 15:27:46 Calling on_part_data with data[0:1]
2023-06-22 15:27:46 Calling on_part_data with data[150063:262144]
2023-06-22 15:27:46 Calling on_part_data with data[0:25359]
2023-06-22 15:27:46 Calling on_part_end with no data
2023-06-22 15:27:46 Calling on_end with no data
2023-06-22 15:27:46 Processing audio
2023-06-22 15:27:46 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:27:46 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:27:46 Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-06-22 15:27:46 Starting new HTTPS connection (1): api.openai.com:443
2023-06-22 15:28:41 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 200 None
2023-06-22 15:28:41 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=5689 request_id=52c54cc45dc618fc88be7cd91fb33b91 response_code=200
2023-06-22 15:28:41 Failed to process audio file
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 58, in audio
    transcript = response[0]['text']
TypeError: string indices must be integers
2023-06-22 15:30:48 Calling on_part_begin with no data
2023-06-22 15:30:48 Calling on_header_field with data[54:73]
2023-06-22 15:30:48 Calling on_header_value with data[75:116]
2023-06-22 15:30:48 Calling on_header_end with no data
2023-06-22 15:30:48 Calling on_headers_finished with no data
2023-06-22 15:30:48 Calling on_part_end with no data
2023-06-22 15:30:48 Calling on_end with no data
2023-06-22 15:30:48 Processing audio
2023-06-22 15:30:48 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:30:48 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:30:48 Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-06-22 15:30:48 Starting new HTTPS connection (1): api.openai.com:443
2023-06-22 15:30:50 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 400 204
2023-06-22 15:30:50 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=185 request_id=dd237db165fe01a3bd63a66e6f966663 response_code=400
2023-06-22 15:30:50 error_code=None error_message="Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-06-22 15:30:50 Failed to process audio file
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 56, in audio
    response = openai.Audio.transcribe("whisper-1", audio_file, response_format="text",language="en")
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_resources/audio.py", line 65, in transcribe
    response, _, api_key = requestor.request("post", url, files=files, params=data)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']
2023-06-22 15:31:20 Calling on_part_begin with no data
2023-06-22 15:31:20 Calling on_header_field with data[54:73]
2023-06-22 15:31:20 Calling on_header_value with data[75:116]
2023-06-22 15:31:20 Calling on_header_end with no data
2023-06-22 15:31:20 Calling on_headers_finished with no data
2023-06-22 15:31:20 Calling on_part_end with no data
2023-06-22 15:31:20 Calling on_end with no data
2023-06-22 15:31:20 Processing audio
2023-06-22 15:31:20 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:31:20 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:31:20 Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-06-22 15:31:20 Starting new HTTPS connection (1): api.openai.com:443
2023-06-22 15:31:22 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 400 204
2023-06-22 15:31:22 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=111 request_id=c13898a016058e90ce3b57a1cb36042c response_code=400
2023-06-22 15:31:22 error_code=None error_message="Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-06-22 15:31:22 Failed to process audio file
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 56, in audio
    response = openai.Audio.transcribe("whisper-1", audio_file, response_format="text",language="en")
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_resources/audio.py", line 65, in transcribe
    response, _, api_key = requestor.request("post", url, files=files, params=data)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']
2023-06-22 15:33:09 Calling on_part_begin with no data
2023-06-22 15:33:09 Calling on_header_field with data[54:73]
2023-06-22 15:33:09 Calling on_header_value with data[75:130]
2023-06-22 15:33:09 Calling on_header_end with no data
2023-06-22 15:33:09 Calling on_header_field with data[132:144]
2023-06-22 15:33:09 Calling on_header_value with data[146:156]
2023-06-22 15:33:09 Calling on_header_end with no data
2023-06-22 15:33:09 Calling on_headers_finished with no data
2023-06-22 15:33:09 Calling on_part_end with no data
2023-06-22 15:33:09 Calling on_end with no data
2023-06-22 15:33:09 Processing audio
2023-06-22 15:33:09 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:33:09 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:33:10 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 400 204
2023-06-22 15:33:10 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=146 request_id=62d1973928899994028fa8be8bf65334 response_code=400
2023-06-22 15:33:10 error_code=None error_message="Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-06-22 15:33:10 Failed to process audio file
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 56, in audio
    response = openai.Audio.transcribe("whisper-1", audio_file, response_format="text",language="en")
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_resources/audio.py", line 65, in transcribe
    response, _, api_key = requestor.request("post", url, files=files, params=data)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']
2023-06-22 15:33:18 Calling on_part_begin with no data
2023-06-22 15:33:18 Calling on_header_field with data[54:73]
2023-06-22 15:33:18 Calling on_header_value with data[75:130]
2023-06-22 15:33:18 Calling on_header_end with no data
2023-06-22 15:33:18 Calling on_header_field with data[132:144]
2023-06-22 15:33:18 Calling on_header_value with data[146:156]
2023-06-22 15:33:18 Calling on_header_end with no data
2023-06-22 15:33:18 Calling on_headers_finished with no data
2023-06-22 15:33:18 Calling on_part_end with no data
2023-06-22 15:33:18 Calling on_end with no data
2023-06-22 15:33:18 Processing audio
2023-06-22 15:33:18 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:33:18 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:33:18 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 400 204
2023-06-22 15:33:18 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=132 request_id=405fced52a94952d21e41c289b95608d response_code=400
2023-06-22 15:33:18 error_code=None error_message="Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-06-22 15:33:18 Failed to process audio file
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 56, in audio
    response = openai.Audio.transcribe("whisper-1", audio_file, response_format="text",language="en")
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_resources/audio.py", line 65, in transcribe
    response, _, api_key = requestor.request("post", url, files=files, params=data)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']
2023-06-22 15:33:39 Calling on_part_begin with no data
2023-06-22 15:33:39 Calling on_header_field with data[54:73]
2023-06-22 15:33:39 Calling on_header_value with data[75:130]
2023-06-22 15:33:39 Calling on_header_end with no data
2023-06-22 15:33:39 Calling on_header_field with data[132:144]
2023-06-22 15:33:39 Calling on_header_value with data[146:156]
2023-06-22 15:33:39 Calling on_header_end with no data
2023-06-22 15:33:39 Calling on_headers_finished with no data
2023-06-22 15:33:39 Calling on_part_end with no data
2023-06-22 15:33:39 Calling on_end with no data
2023-06-22 15:33:39 Processing audio
2023-06-22 15:33:39 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:33:39 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:33:39 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 400 204
2023-06-22 15:33:39 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=28 request_id=e6f7f56c236be184e5ead12ca4847f34 response_code=400
2023-06-22 15:33:39 error_code=None error_message="Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-06-22 15:33:39 Failed to process audio file
Traceback (most recent call last):
  File "/home/alan/riktam/speech-to-text/whisper.py", line 56, in audio
    response = openai.Audio.transcribe("whisper-1", audio_file, response_format="text",language="en")
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_resources/audio.py", line 65, in transcribe
    response, _, api_key = requestor.request("post", url, files=files, params=data)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/alan/riktam/speech-to-text/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']
2023-06-22 15:42:21 Calling on_part_begin with no data
2023-06-22 15:42:21 Calling on_header_field with data[54:73]
2023-06-22 15:42:21 Calling on_header_value with data[75:148]
2023-06-22 15:42:21 Calling on_header_end with no data
2023-06-22 15:42:21 Calling on_header_field with data[150:162]
2023-06-22 15:42:21 Calling on_header_value with data[164:173]
2023-06-22 15:42:21 Calling on_header_end with no data
2023-06-22 15:42:21 Calling on_headers_finished with no data
2023-06-22 15:42:21 Calling on_part_data with data[177:25565]
2023-06-22 15:42:21 Calling on_part_data with data[0:1]
2023-06-22 15:42:21 Calling on_part_data with data[25566:65713]
2023-06-22 15:42:21 Calling on_part_data with data[0:6107]
2023-06-22 15:42:21 Calling on_part_data with data[0:1]
2023-06-22 15:42:21 Calling on_part_data with data[6108:89599]
2023-06-22 15:42:21 Calling on_part_data with data[0:1]
2023-06-22 15:42:21 Calling on_part_data with data[89600:262144]
2023-06-22 15:42:21 Calling on_part_data with data[0:137181]
2023-06-22 15:42:21 Calling on_part_data with data[0:1]
2023-06-22 15:42:21 Calling on_part_data with data[137182:187194]
2023-06-22 15:42:21 Calling on_part_data with data[0:1]
2023-06-22 15:42:21 Calling on_part_data with data[187195:262144]
2023-06-22 15:42:21 Calling on_part_data with data[0:230870]
2023-06-22 15:42:21 Calling on_part_data with data[0:1]
2023-06-22 15:42:21 Calling on_part_data with data[230871:262144]
2023-06-22 15:42:21 Calling on_part_data with data[0:10921]
2023-06-22 15:42:21 Calling on_part_data with data[0:1]
2023-06-22 15:42:21 Calling on_part_data with data[10922:150062]
2023-06-22 15:42:21 Calling on_part_data with data[0:1]
2023-06-22 15:42:21 Calling on_part_data with data[150063:262144]
2023-06-22 15:42:21 Calling on_part_data with data[0:25359]
2023-06-22 15:42:21 Calling on_part_end with no data
2023-06-22 15:42:21 Calling on_end with no data
2023-06-22 15:42:21 Processing audio
2023-06-22 15:42:21 message='Request to OpenAI API' method=post path=https://api.openai.com/v1/audio/transcriptions
2023-06-22 15:42:21 api_version=None data="{'model': 'whisper-1', 'response_format': 'text', 'language': 'en'}" message='Post details'
2023-06-22 15:42:21 Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-06-22 15:42:21 Starting new HTTPS connection (1): api.openai.com:443
2023-06-22 15:47:17 https://api.openai.com:443 "POST /v1/audio/transcriptions HTTP/1.1" 200 None
2023-06-22 15:47:17 message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=5230 request_id=d036f3d41bd5c146384075f599dfae7f response_code=200
